OUTPUTDIR= output

default: all

include Makefile.files

.PHONY: clean
clean:
	rm -f $(OUTPUTDIR)/*   
	rm -f bin/gte
	rm -rf bin/resources

all: $(OUTPUTDIR) bin depend gtedemo engine graphics animation debug geometry gtemath base global engineobjects asset util image filesystem inputmanager error
	$(CC)  $(OBJECTFILES) -o bin/gtedemo $(LIBS)  
	rm -rf bin/resources
	cp -r resources bin/

.PHONY: depend
depend: 
	@./srcdep.sh $(ALLSRCS)
	
$(OUTPUTDIR): 
	mkdir $(OUTPUTDIR)
	
bin:
	mkdir bin

