uniform mat4 MODELVIEWPROJECTION_MATRIX;; 
attribute vec4 SHADOW_POSITION;
uniform vec4 LIGHT_POSITION;

void main()
{	
	vec4 dir = SHADOW_POSITION.w == 0.0 ? vec4(SHADOW_POSITION.xyz * LIGHT_POSITION.w - LIGHT_POSITION.xyz, 0.0) : SHADOW_POSITION;
    gl_Position = MODELVIEWPROJECTION_MATRIX * dir;
}